---
title: "| CUHK STAT5060\n| Advanced Modeling and Data Analysis \n"
author: |
  | Benjamin Chan
  | November 19, 2018
output: html_document
subtitle: |
  | Multilevel Analysis of School Examination Data
  | Submodel with Random and Fixed Intercept, without School Effect Predictor
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

### Install Packages
```{r, warning = FALSE, message = FALSE}
# Check if packages are installed. If not, install them.
install.new.packages <- function(pkg) {
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) {
        install.packages(new.pkg)
    }
}

packages <- c("R2WinBUGS", "mcmcplots", "knitr", "kableExtra")
install.new.packages(packages)
```

### Load Packages
```{r, warning = FALSE, message = FALSE}
library(R2WinBUGS)                            # Running WinBUGS from R
library(mcmcplots)                            # Create Plots from MCMC Output
library(knitr)                                # Dynamic Report Generation
library(kableExtra)                           # Construct Complex Table and Pipe Syntax
```

### Read in Data
```{r}
Sys.time()

d <- read.csv("./../Dataset/Exam_Full.csv", header = T)
colnames(d)

!is.unsorted(d[, 2])                          # Test if School.ID is sorted in increasing order

d$School.ID <- as.factor(d$School.ID)
cluster <- levels(d$School.ID)

d <- read.csv("./../Dataset/Exam_Full.csv", header = T)
d <- as.matrix(d)
```

### Set-up for WinBUGS
```{r}
(J <- length(cluster))                        # Number of schools (clusters)
nj <- rep(NA, J)

for (j in 1:J) {
    nj[j] <- sum(d[, 2] == cluster[j])
}

cum.nj <- cumsum(nj)
(cum.nj <- c(0, cum.nj))                      # Cut-offs

# Student level covariates:
# LR.Test.Score, Student.Gender, Student.VR.Mid, Student.VR.Top, Student.Band.Mid, Student.Band.Top
X <- d[, c(4:5, 9:12)]

Y <- d[, 3]

data = list(X = X, Y = Y, J = J, cum.nj = cum.nj)

init1 <- list(beta0 = 0, beta = c(0, 0, 0, 0, 0, 0), phi0 = 1, psi = 1)
init2 <- list(beta0 = 0, beta = c(1, -1, 1, -1, -1, -1), phi0 = 0.5, psi = 0.5)
inits <- list(init1, init2)

parameters = c("beta0", "beta", "var_u0", "var_y")
```

### Bayesian Results
```{r}
model <- bugs(data, inits, parameters, 
              model.file = "submodel_with_intercept_without_school_effect_predictor.txt", 
              n.chains = 2, n.iter = 14000, n.burnin = 8000, n.thin = 1, DIC = TRUE,
              bugs.directory = "C:/Users/s1155049861/Desktop/STAT5020/Source/WinBUGS14/")

# Disseminated Intravascular Coagulation (DIC)
model$DIC
```

#### Means and Standard Errors of Parameter Estimates
```{r}
# Extract summary statistics
summary <- model$summary[-nrow(model$summary), c("mean", "sd", "2.5%", "97.5%")]
summary <- as.data.frame(round(summary, 2))

colnames(summary) <- c("Mean", "SE", "2.5%", "97.5%")
Variable <- c("y_Int", colnames(X), "var_u0", "var_y")
summary <- cbind(Variable, summary)

summary$Contain_0 <- ifelse(summary$"2.5%"< 0 & summary$"97.5%" > 0, "Y", "N")
summary$Significant <- ifelse(summary$Contain_0 == "N", "*", "")
significant_row <- which(summary$Contain_0 == "N")

kable(summary, format = "markdown", align = "c")

print(kable(summary, format = "latex", align = "c") %>%
      add_header_above(c("","", "Estimate" = 2, "95% CI" = 2, "Significance" = 2)))
```

#### Running Mean Plots
```{r}
rmeanplot(model, parms = "beta", style = "plain")

rmeanplot(model, parms = "var_u0", style = "plain")
rmeanplot(model, parms = "var_y", style = "plain")
```